# Generated by Django 3.1.6 on 2021-02-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('abbreviation', models.CharField(max_length=2)),
                ('vat_deadline', models.CharField(max_length=40)),
                ('ec_sales_deadline', models.CharField(max_length=40)),
                ('intrastat_deadline', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.country')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=12)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.country')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.division')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_type', models.CharField(choices=[('VAT', 'VAT Return'), ('INT', 'Intrastat'), ('ECS', 'EC Sales List')], default='VAT', max_length=3)),
                ('month', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=40)),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('is_payable', models.BooleanField(default=False)),
                ('payable_receivable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('time_budget', models.IntegerField()),
                ('is_submitted_for_review', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_filed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=100)),
                ('completion_pct', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.country')),
                ('tax_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.taxregistration')),
            ],
        ),
    ]
