# Generated by Django 3.1.6 on 2021-02-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(default='AA', max_length=2),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='aa', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='name',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='ec_sales_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='intrastat_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='vat_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='division',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.country'),
        ),
    ]
