# Generated by Django 3.1.6 on 2021-02-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_newclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Declaration',
        ),
    ]
