# Generated by Django 3.1.6 on 2021-02-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0003_delete_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_type', models.CharField(choices=[('VAT', 'VAT Return'), ('INT', 'Intrastat'), ('ECS', 'EC Sales List')], default='VAT', max_length=3)),
                ('month', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=40)),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('is_payable', models.BooleanField(default=False)),
                ('payable_receivable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('time_budget', models.IntegerField()),
                ('is_submitted_for_review', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_filed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=100)),
                ('completion_pct', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.country')),
                ('preparer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparer', to=settings.AUTH_USER_MODEL)),
                ('tax_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.taxregistration')),
            ],
        ),
        migrations.DeleteModel(
            name='newClass',
        ),
    ]
