# Generated by Django 3.1.6 on 2021-02-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0004_auto_20210207_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='completion_pct',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.country'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='month',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='preparer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='status',
            field=models.CharField(default='not started', max_length=100),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='tax_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.taxregistration'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='time_budget',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='year',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
