# Generated by Django 3.1.6 on 2021-02-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_auto_20210204_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='compliance.division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declaration',
            name='payable_receivable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
