# Generated by Django 3.1.6 on 2021-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_auto_20210204_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='division',
            field=models.CharField(max_length=40),
        ),
    ]
