# Generated by Django 3.1.6 on 2021-02-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_delete_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_type', models.CharField(choices=[('VAT', 'VAT Return'), ('INT', 'Intrastat'), ('ECS', 'EC Sales List')], default='VAT', max_length=3)),
                ('division', models.CharField(max_length=40)),
                ('month', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=40)),
                ('is_payable', models.BooleanField(default=False)),
                ('payable_receivable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preparer', models.CharField(max_length=40)),
                ('time_budget', models.IntegerField()),
                ('is_submitted_for_review', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_filed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.country')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.teammember')),
            ],
        ),
    ]
