# Generated by Django 3.1.6 on 2021-02-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_declaration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tax_Registration',
            new_name='TaxRegistration',
        ),
    ]
