# Generated by Django 3.1.6 on 2021-02-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_auto_20210205_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='status',
            field=models.CharField(default='In progress', max_length=100),
            preserve_default=False,
        ),
    ]
