# Generated by Django 3.1.6 on 2021-02-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_declaration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='tax_registration',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='compliance.taxregistration'),
            preserve_default=False,
        ),
    ]
