# Generated by Django 3.1.6 on 2021-02-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_declaration_tax_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='year',
        ),
        migrations.AddField(
            model_name='declaration',
            name='period_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='period_start',
            field=models.DateField(null=True),
        ),
    ]
