# Generated by Django 3.1.6 on 2021-02-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_auto_20210205_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='year',
            field=models.CharField(default='2020', max_length=40),
            preserve_default=False,
        ),
    ]
