# Generated by Django 3.1.6 on 2021-02-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_declaration_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='completion_pct',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
