# Generated by Django 3.1.6 on 2021-02-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0015_declaration_completion_pct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxregistration',
            old_name='divsion',
            new_name='division',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='division',
        ),
    ]
