# Generated by Django 3.1.6 on 2021-02-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_auto_20210205_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='reviewer',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
