# Generated by Django 3.1.6 on 2021-02-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0017_auto_20210206_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='preparer',
        ),
    ]
