# Generated by Django 3.1.6 on 2021-02-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0019_auto_20210207_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='preparer',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='reviewer',
        ),
    ]
